### ISSUE TITLE
-v, --verbose mode needed

### ISSUE THREAD

**Issue by whoizit** [FilippoRanza/rmd#1]
I would like to see which files are deleted and when specifying -vv I would like to see also how much space is freed up (total)

**Comment by FilippoRanza** [comment]
I'll add a verbose mode

**Comment by FilippoRanza** [comment]
I've added _verbose_ and _very verbose_ mode. The first one simply output the path of the removed file, the second also show the file type (if it is a directory or not), the size of the single removed file and, at the end, the total freed space, the number of removed files and directories
