### ISSUE TITLE
remove empty dirs

### ISSUE THREAD

**Issue by whoizit** [FilippoRanza/rmd#2]
after rmd works, empty directories remain. It would be nice to have the option to delete the directory if it is empty after rmd work

**Comment by FilippoRanza** [comment]
You're right. This is an important feature to add, I'll work as soon as possible

**Comment by FilippoRanza** [comment]
I add the -c flag to optionally clean (remove) empty directories after an automatic removal. By default this flag is set to false so the rmd behavior remains coherent with the previous versions
