### ISSUE TITLE
ability to skip DVCS repos and others

### ISSUE THREAD

**Issue by whoizit** [FilippoRanza/rmd#4]
```
Remove Directory: "/home/d/sync/work/new-project/.git/branches"
Remove Directory: "/home/d/sync/work/new-project/.git/objects/info"
Remove Directory: "/home/d/sync/work/new-project/.git/objects/pack"
Remove Directory: "/home/d/sync/work/new-project/.git/objects"
Remove Directory: "/home/d/sync/work/new-project/.git/refs/tags"
Remove Directory: "/home/d/sync/work/new-project/.git/refs/heads"
Remove Directory: "/home/d/sync/work/new-project/.git/refs"

```

**Comment by whoizit** [comment]
Problem with syncthing
```
Remove Directory: "/home/d/sync/igor-mob/.stfolder"
Remove Directory: "/home/d/sync/igor-cam-b/.stfolder"
Remove Directory: "/home/d/sync/keepassxc/.stfolder"
Remove File: "/home/d/sync/music/.stfolder (1)/DO_NOT_DELETE.txt" - freed 13.00 b
Remove Directory: "/home/d/sync/music/.stfolder (1)"
Remove Directory: "/home/d/sync/music/.stfolder"
Remove File: "/home/d/sync/music/.stignore" - freed 0.00 b
Remove File: "/home/d/sync/backup/.stfolder (1)/DO_NOT_DELETE.txt" - freed 13.00 b
Remove Directory: "/home/d/sync/backup/.stfolder (1)"
Remove Directory: "/home/d/sync/backup/.config"
Remove Directory: "/home/d/sync/backup/.stfolder"
Remove File: "/home/d/sync/backup/.stignore" - freed 0.00 b
Remove Directory: "/home/d/sync/igor-cam/.stfolder"
Remove File: "/home/d/sync/work/.stfolder (1)/DO_NOT_DELETE.txt" - freed 13.00 b
Remove Directory: "/home/d/sync/work/.stfolder (1)"
```
![2020-06-08_01:58:52_1384x366_grim](https://user-images.githubusercontent.com/359276/83982027-a7ac5b80-a92b-11ea-8113-e14d397d5e17.png)

**Comment by FilippoRanza** [comment]
I hope that this does not cause to many issues, anyway I'll add an '--ignore' option as soon as possible

**Comment by FilippoRanza** [comment]
Now it is possible to skip files by extension and skip directories by name.

**Comment by whoizit** [comment]
it would be nice to have a default config so that everyone doesn't have to add '.git .hg .stfolder* .stversions' and many-many others to ignore

**Comment by FilippoRanza** [comment]
I understand your point about a configuration file, but I think that it will add an unnecessary complexity. I think that, for now, it is a better and simpler solution to simply wrap **rmd** into a shell function like 
```bash
function rmd() {
   rmd --ignore-directories .git .hg "$@"
}
```
Probably in a future version I'll add something like a configuration file(it is a very reasonable idea), but this feature will not be implemented in the next version (0.5.0)

**Comment by FilippoRanza** [comment]
I've noticed that you've written *.strfolder**. Probably it is a typo but at the current time both extension and directory skip works only with exact matches and does not support regex. I'll add support for regex to those flags in a future version.

**Comment by whoizit** [comment]
I assume that the configuration file for rmd is superfluous. In this case, you should create a wiki page describing the useful alias like `alias rmdd='rmd --ignore-directories .* --ignore-extensions .*'` or simply add option `--ignore-dots` 

seems to be `--ignore-dots` enough for me atm.

**Comment by FilippoRanza** [comment]
I'll add some advices like aliases  or shell functions in the [documentation](https://filipporanza.github.io/rmd/), I prefer to keep everything in the same place.  ```--ignore-dots``` or more clearly ```--ignore-unix-hidden``` is a good idea, although 
it will work only on *nix systems. I'll implement it as soon as possible

**Comment by FilippoRanza** [comment]
```--ignore-unix-hidden``` is implemented. I close this issue. Thanks again for your advice and your patience
