### ISSUE TITLE
Warning message to removing duplicate files.

### ISSUE THREAD

**Issue by dhra** [FilippoRanza/rmd#5]
I'm trying to remove duplicate files and here is warning message:
```bash
~/rmd/: echo 123>>a
~/rmd/: echo 123>>b
~/rmd/: echo 123>>c
~/rmd/: rmd -v -d -i
remove: .?

``` 
Warning message should be something like this:
```bash
Are you sure to remove: [a, b]? y/n
```

**Comment by FilippoRanza** [comment]
You are right, I'll take a look immediately

**Comment by FilippoRanza** [comment]
Now ```rmd``` during an automatic removal in interactive  asks for each file before remove it. 
So in your example 
```bash
~/rmd/: echo 123>>a
~/rmd/: echo 123>>b
~/rmd/: echo 123>>c
~/rmd/: echo 234>>d

~/rmd/: rmd -d -i
remove: ./b ? y/N
remove: ./c ? y/N
```
Assuming that directory is iterated in alphabetical order, ```a``` is the first file and is considered as the main version, ```b``` and ```c``` are duplicates so ```rmd``` ask for removal. ```d``` is  unique and is left untouched.

**Comment by FilippoRanza** [comment]
I've just updated the documentation. I consider ```rmd``` fixed and close this issue. Thanks for your feedback
